### ISSUE TITLE
Wheels for more platforms

### ISSUE THREAD

**Issue by alugowski** [michelemartone/pyrsb#13]
I would love to try librsb, but the [wheels available on PyPI](https://pypi.org/project/pyrsb/#files) are for old Python versions on Linux only.

`pip install pyrsb`  attempts to build from source, but in a clean venv (with just numpy installed) throws this:

```
% pip install pyrsb
Collecting pyrsb
  Using cached pyrsb-0.2.20220404.2.tar.gz (29 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/enos/temp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/enos/temp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/enos/temp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/kw/m9k1cybd0qn671gwqr3v3lyh0000gn/T/pip-build-env-cau9js3n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/kw/m9k1cybd0qn671gwqr3v3lyh0000gn/T/pip-build-env-cau9js3n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/kw/m9k1cybd0qn671gwqr3v3lyh0000gn/T/pip-build-env-cau9js3n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/kw/m9k1cybd0qn671gwqr3v3lyh0000gn/T/pip-build-env-cau9js3n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

I'm on an M1 mac.

**Comment by michelemartone** [comment]
Hi @alugowski . Thanks for feedback. I won't be proactive during these (holiday) days so I can check the `pip` issue later on.

Compiling LIBRSB on one own's machine is always the best thing and it's pretty easy -- let know if you encounter problems with that or if anything in LIBRSB's instructions is wrong or missing about that.

**Comment by michelemartone** [comment]
Hi @alugowski . Were you able to proceed by your own?

**Comment by alugowski** [comment]
> Hi @alugowski . Were you able to proceed by your own?

I glanced through the build process before submitting the issue. I've no idea why it gets stuck at the place it does. I do notice a few issues in the build system, but more importantly I saw the message that this is just a prototype. That, combined with only being tested on old Linux and using a no-longer supported build system makes me not want to commit more time. Like I said, I just wanted to give this a quick try to see what's up, I'm not motivated to spend hours debugging.

**Comment by alugowski** [comment]
FYI, building wheels for all common platforms is no longer the big hassle it used to be. GitHub Actions and cibuildwheel make it easy.

**Comment by michelemartone** [comment]
Hi @alugowski . PyRSB is a prototype: it's only a thin layer to the LIBRSB library, which is perfectly mature.
